package com.example.diabetesmanage.controller.patient;

import com.example.diabetesmanage.dao.DietPlanDAO;
import com.example.diabetesmanage.dao.HealthRecordDAO;
import com.example.diabetesmanage.dao.MasterFoodDAO;
import com.example.diabetesmanage.dao.PatientDAO;
import com.example.diabetesmanage.model.DietPlan;
import com.example.diabetesmanage.model.DietPlanDetail;
import com.example.diabetesmanage.model.HealthRecord;
import com.example.diabetesmanage.model.MasterFood;
import com.example.diabetesmanage.model.Patient;
import com.example.diabetesmanage.service.GeminiService;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@WebServlet("/patient-diet")
public class PatientDietServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        PatientDAO patientDAO = new PatientDAO();
        String patientId = patientDAO.getDemoPatientId();
        
        if (patientId == null) {
            response.sendRedirect(request.getContextPath() + "/patient-dashboard");
            return;
        }

        DietPlanDAO dietPlanDAO = new DietPlanDAO();
        DietPlan todayPlan = dietPlanDAO.getTodayDietPlan(patientId);
        
        Patient patientInfo = patientDAO.getPatientById(patientId);
        request.setAttribute("patientInfo", patientInfo);
        
        request.setAttribute("todayPlan", todayPlan);
        
        request.getRequestDispatcher("/WEB-INF/views/patient/patient-diet.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String action = request.getParameter("action");
        if ("generate".equals(action)) {
            PatientDAO patientDAO = new PatientDAO();
            String patientId = patientDAO.getDemoPatientId();
            
            if (patientId != null) {
                Patient patient = patientDAO.getPatientById(patientId);
                HealthRecordDAO hrDAO = new HealthRecordDAO();
                HealthRecord record = hrDAO.getLatestComprehensiveRecord(patientId);
                
                MasterFoodDAO foodDAO = new MasterFoodDAO();
                // Filter only active foods
                List<MasterFood> foods = foodDAO.getAllFoods().stream()
                        .filter(MasterFood::isTrangThai)
                        .collect(Collectors.toList());
                        
                GeminiService geminiService = new GeminiService();
                String jsonResponse = geminiService.generateDailyDietPlan(patient, record, foods);
                
                try {
                    Gson gson = new Gson();
                    Type listType = new TypeToken<List<DietPlanDetail>>(){}.getType();
                    List<DietPlanDetail> details = gson.fromJson(jsonResponse, listType);
                    
                    if (details != null && !details.isEmpty()) {
                        DietPlan plan = new DietPlan();
                        plan.setId(UUID.randomUUID().toString());
                        plan.setPatientId(patientId);
                        plan.setDoctorId("AI_SYSTEM"); // Generated by AI
                        plan.setGhiChu("Thực đơn được tạo tự động bởi AI dựa trên chỉ số sức khỏe của bạn.");
                        
                        List<DietPlanDetail> validDetails = new ArrayList<>();
                        for (DietPlanDetail d : details) {
                            d.setId(UUID.randomUUID().toString());
                            d.setDietPlanId(plan.getId());
                            validDetails.add(d);
                        }
                        plan.setChiTietThucPham(validDetails);
                        
                        DietPlanDAO planDAO = new DietPlanDAO();
                        
                        // Xóa các thực đơn cũ trong ngày của AI để tránh trùng lặp
                        try (java.sql.Connection conn = com.example.diabetesmanage.util.DBContext.getConnection();
                             java.sql.PreparedStatement ps = conn.prepareStatement("DELETE FROM diet_plans WHERE patient_id = ? AND DATE(ngay_tao) = CURDATE() AND doctor_id = 'AI_SYSTEM'")) {
                            ps.setString(1, patientId);
                            ps.executeUpdate();
                        } catch (Exception e) {}

                        planDAO.saveDietPlan(plan);
                        request.getSession().setAttribute("msgSuccess", "Đã gợi ý thực đơn AI thành công!");
                    } else {
                        request.getSession().setAttribute("msgError", "Hệ thống AI hiện đang bận hoặc quá tải. Vui lòng thử lại sau.");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    request.getSession().setAttribute("msgError", "Hệ thống AI hiện đang bận hoặc quá tải. Vui lòng thử lại sau.");
                }
            }
        }
        
        response.sendRedirect(request.getContextPath() + "/patient-diet");
    }
}
